In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_excel('new_data.xlsx')
data.head()

  governate              city station_name destination  price
0   القاهرة  حى الساحل - شبرا         عبود       دمياط  110.0
1   القاهرة  حى الساحل - شبرا         عبود    رأس البر  140.0
2   القاهرة  حى الساحل - شبرا         عبود   كفر الشيخ   59.0
3   القاهرة  حى الساحل - شبرا         عبود        قلين   60.0
4   القاهرة  حى الساحل - شبرا         عبود     الحامول   65.0

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1409 entries, 0 to 1408
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   governate     1409 non-null   object
 1   city          1409 non-null   object
 2   station_name  1409 non-null   object
 3   destination   1409 non-null   object
 4   price         1409 non-null   float64
dtypes: float64(1), object(4)
memory usage: 55.2+ KB

In [4]:
data.describe()

             price
count  1409.000000
mean     25.110539
std      41.216828
min       3.000000
25%       5.500000
50%       8.000000
75%      29.500000
max     390.000000

In [5]:
data.describe(include='object')

       governate      city station_name destination
count       1409      1409         1409        1409
unique         5        48          129         839
top     الدقهلية  بنى سويف     بنى سويف  الإسكندرية
freq         435        70           70          23

In [6]:
data.isna().sum()

governate       0
city            0
station_name    0
destination     0
price           0
dtype: int64

In [7]:
data.duplicated().sum()

1

In [10]:
data[data.duplicated()==True]

    governate city station_name destination  price
305  بنى سويف  ببا          ببا    البرانقة    5.0

In [11]:
data[data['city']=='ببا']

    governate city station_name      destination  price
272  بنى سويف  ببا          ببا           المنيب   69.0
273  بنى سويف  ببا          ببا         بنى سويف    8.0
274  بنى سويف  ببا          ببا            المرج   77.0
275  بنى سويف  ببا          ببا       الإسكندرية  204.0
276  بنى سويف  ببا          ببا         السلطانى    5.0
277  بنى سويف  ببا          ببا         بنى قاسم    5.0
278  بنى سويف  ببا          ببا         البرانقة    5.0
279  بنى سويف  ببا          ببا    طنسا بنى مالو    5.0
280  بنى سويف  ببا          ببا       منشأة عاصم    5.0
281  بنى سويف  ببا          ببا      سدس الأمراء    5.0
282  بنى سويف  ببا          ببا             شوشة    5.0
283  بنى سويف  ببا          ببا           هربشنت    5.0
284  بنى سويف  ببا          ببا             سراج    5.0
285  بنى سويف  ببا          ببا         الشراهنة    5.0
286  بنى سويف  ببا          ببا            الفشن    6.0
287  بنى سويف  ببا          ببا            طرشوب    5.0
288  بنى سويف  ببا          ببا        أبو شربان    5.0
289  بنى سويف  ببا          ببا           البرقى    5.0
290  بنى سويف  ببا          ببا         صفط رشين    5.0
291  بنى سويف  ببا          ببا        بنى مؤمنة    5.0
292  بنى سويف  ببا          ببا          المزرعة    5.0
293  بنى سويف  ببا          ببا            دشطوط    6.0
294  بنى سويف  ببا          ببا    عمار والزاوية    7.0
295  بنى سويف  ببا          ببا      لوبى المحيط    5.0
296  بنى سويف  ببا          ببا         عزبة هوس    5.0
297  بنى سويف  ببا          ببا           الشريف    5.0
298  بنى سويف  ببا          ببا           الإمام    5.0
299  بنى سويف  ببا          ببا     قنبش الحمراء    5.0
300  بنى سويف  ببا          ببا         كفر ناصر    5.0
301  بنى سويف  ببا          ببا        عزبة نجيب    5.0
302  بنى سويف  ببا          ببا          أبو عدس    5.0
303  بنى سويف  ببا          ببا            غياضة    5.0
304  بنى سويف  ببا          ببا         بنى ماضى    5.0
305  بنى سويف  ببا          ببا         البرانقة    5.0
306  بنى سويف  ببا          ببا        كفر منصور    5.0
307  بنى سويف  ببا          ببا           اسكندر    5.0
308  بنى سويف  ببا          ببا         الضباعنة    5.0
309  بنى سويف  ببا          ببا        سدس البلد    5.0
310  بنى سويف  ببا          ببا            برامل    5.0
311  بنى سويف  ببا          ببا             بدهل    5.0
312  بنى سويف  ببا          ببا    رزقة المشارقة    5.0
313  بنى سويف  ببا          ببا  نزلة على كيلانى    5.0
314  بنى سويف  ببا          ببا       طحا البيشة    5.0
315  بنى سويف  ببا          ببا             هلية    5.0
316  بنى سويف  ببا          ببا            سمسطا    7.0
317  بنى سويف  ببا          ببا     كوم الصعايدة    6.0

In [12]:
data.drop_duplicates(inplace=True)

In [13]:
data['city'].unique()

array(['حى الساحل - شبرا', 'السلام', 'المرج', 'حلوان', 'بنى سويف', 'ببا',
       'الفشن', 'إهناسيا', 'سمسطا', 'ناصر ', 'الواسطى', 'كفر سعد',
       'كفر البطيخ', 'كفر الغاب', 'دمياط الجديدة', 'دمياط',
       'ميت أبو غالب', 'رأس البر', 'الزرقا', 'الوسطانى', 'فارسكور',
       'الروضة', 'الباجور', 'تلا', 'السادات', 'سرس الليان', 'منوف',
       'قويسنا', 'الشهداء', 'بركة السبع', 'شبين الكوم', 'أشمون',
       'المنصورة', 'طلخا', 'أجا', 'ميت غمر', 'دكرنس', 'منية النصر',
       'ميت سلسيل', 'الجمالية', 'المنزلة', 'نبروه', 'بلقاس', 'شربين',
       'جمصة', 'السنبلاوين', 'تمى الأمديد', 'بنى عبيد'], dtype=object)

In [14]:
data['city']=data['city'].str.strip()
data['city'].unique()

array(['حى الساحل - شبرا', 'السلام', 'المرج', 'حلوان', 'بنى سويف', 'ببا',
       'الفشن', 'إهناسيا', 'سمسطا', 'ناصر', 'الواسطى', 'كفر سعد',
       'كفر البطيخ', 'كفر الغاب', 'دمياط الجديدة', 'دمياط',
       'ميت أبو غالب', 'رأس البر', 'الزرقا', 'الوسطانى', 'فارسكور',
       'الروضة', 'الباجور', 'تلا', 'السادات', 'سرس الليان', 'منوف',
       'قويسنا', 'الشهداء', 'بركة السبع', 'شبين الكوم', 'أشمون',
       'المنصورة', 'طلخا', 'أجا', 'ميت غمر', 'دكرنس', 'منية النصر',
       'ميت سلسيل', 'الجمالية', 'المنزلة', 'نبروه', 'بلقاس', 'شربين',
       'جمصة', 'السنبلاوين', 'تمى الأمديد', 'بنى عبيد'], dtype=object)

In [15]:
data['governate'].unique()

array(['القاهرة', 'بنى سويف', 'دمياط', 'المنوفية', 'الدقهلية'],
      dtype=object)

In [16]:
data['governate']=data['governate'].str.strip()
data['governate'].unique()

array(['القاهرة', 'بنى سويف', 'دمياط', 'المنوفية', 'الدقهلية'],
      dtype=object)

In [17]:
data['station_name'].unique()

array(['عبود', 'السلام', 'المرج', 'عين حلوان', 'بنى سويف', 'ببا', 'الفشن',
       'إهناسيا', 'سمسطا', 'ناصر ', 'الواسطى', 'كفر سعد', 'الوسطانى',
       'كفر الغاب', 'رأس البر', 'كفر البطيخ', 'أم الرضا', 'كفر الشيخ',
       'ميت أبو غالب', 'دمياط', 'دمياط الجديدة', 'الزرقا', 'فارسكور',
       'الروضة', 'الباجور', 'تلا', 'زرقان', 'زاوية بمم', 'كفر داوود',
       'الخطاطبة', 'السادات', 'سرس الليان', 'منوف', 'قويسنا', 'ميت بره',
       'الشهداء', 'نادر', 'العراقية', 'بركة السبع', 'كفر هلال',
       'شبين الكوم', 'أشمون', 'سنتريس', 'شنشور', 'الرملة', 'طليا',
       'ساقية أبو شعرة', 'الأتوبيس الجديد', 'قولونجيل',
       'موقف سندوب العمومى', 'كوم الدربى', 'طناح', 'ميت خميس',
       'الموقف الجديد', 'موقف ديمره', 'موقف بطره', 'موقف ميت عنتر',
       'موقف ميت الكرما', 'موقف المنصورة', 'بحور كوبرى العاشر',
       'أمام نفق السكة الجديد', 'أمام الإدارة الزراعية',
       'محطة الأتوبيس القديم', 'تقاطع 26 يوليو', 'مصر للسياحة',
       '23 يوليو', 'البرامبل', 'دماص', 'شارع العاشر من رمضان', 'النقراشى',
       'المنياوى', 'القاهرة', 'المنصورة', 'المحطة', 'الجوابر', 'العمومى',
       'كوبرى بحارة العيد', 'ميدان الكباس', 'كوبرى قشطة',
       'موقف المنزلة العمومى', 'دكرنس', 'الجمالية', 'النسايمة', 'المطرية',
       'مجمع مواقف', 'بهوت', 'الطيبة', 'تيرة', 'بانوب', 'بانوب ', 'نشا',
       'طنيخ', 'ميدان المحطة', 'جمصة', 'بسنديلة ودمياط', 'قراش',
       'أبو دشيشة', 'الكردود', 'أبو طه', 'قلابشو', 'جالية', 'الجرايدة',
       'شرقية المعصرة', 'الستامونى والحفير', 'موقف شربين العمومى',
       'موقف كفور الغاب', 'موقف بلقاس', 'الضهرية', 'الحصص', 'منشأة النصر',
       'أبو زاهر', 'كفر الترعة', 'بدواى', 'ديسط', 'موقف جمصة العمومى',
       'الزقازيق', 'ميت غمر', 'قرقيرة', 'ظفر', 'أبو ياسين', 'كفر صقر',
       'الحصاينة', 'ميت غراب', 'الجلالية', 'السمارة', 'مجمع', 'ميت فارس',
       'الصلاحات', 'بنى عبيد'], dtype=object)

In [18]:
data['station_name']=data['station_name'].str.strip()
data['station_name'].unique()

array(['عبود', 'السلام', 'المرج', 'عين حلوان', 'بنى سويف', 'ببا', 'الفشن',
       'إهناسيا', 'سمسطا', 'ناصر', 'الواسطى', 'كفر سعد', 'الوسطانى',
       'كفر الغاب', 'رأس البر', 'كفر البطيخ', 'أم الرضا', 'كفر الشيخ',
       'ميت أبو غالب', 'دمياط', 'دمياط الجديدة', 'الزرقا', 'فارسكور',
       'الروضة', 'الباجور', 'تلا', 'زرقان', 'زاوية بمم', 'كفر داوود',
       'الخطاطبة', 'السادات', 'سرس الليان', 'منوف', 'قويسنا', 'ميت بره',
       'الشهداء', 'نادر', 'العراقية', 'بركة السبع', 'كفر هلال',
       'شبين الكوم', 'أشمون', 'سنتريس', 'شنشور', 'الرملة', 'طليا',
       'ساقية أبو شعرة', 'الأتوبيس الجديد', 'قولونجيل',
       'موقف سندوب العمومى', 'كوم الدربى', 'طناح', 'ميت خميس',
       'الموقف الجديد', 'موقف ديمره', 'موقف بطره', 'موقف ميت عنتر',
       'موقف ميت الكرما', 'موقف المنصورة', 'بحور كوبرى العاشر',
       'أمام نفق السكة الجديد', 'أمام الإدارة الزراعية',
       'محطة الأتوبيس القديم', 'تقاطع 26 يوليو', 'مصر للسياحة',
       '23 يوليو', 'البرامبل', 'دماص', 'شارع العاشر من رمضان', 'النقراشى',
       'المنياوى', 'القاهرة', 'المنصورة', 'المحطة', 'الجوابر', 'العمومى',
       'كوبرى بحارة العيد', 'ميدان الكباس', 'كوبرى قشطة',
       'موقف المنزلة العمومى', 'دكرنس', 'الجمالية', 'النسايمة', 'المطرية',
       'مجمع مواقف', 'بهوت', 'الطيبة', 'تيرة', 'بانوب', 'نشا', 'طنيخ',
       'ميدان المحطة', 'جمصة', 'بسنديلة ودمياط', 'قراش', 'أبو دشيشة',
       'الكردود', 'أبو طه', 'قلابشو', 'جالية', 'الجرايدة',
       'شرقية المعصرة', 'الستامونى والحفير', 'موقف شربين العمومى',
       'موقف كفور الغاب', 'موقف بلقاس', 'الضهرية', 'الحصص', 'منشأة النصر',
       'أبو زاهر', 'كفر الترعة', 'بدواى', 'ديسط', 'موقف جمصة العمومى',
       'الزقازيق', 'ميت غمر', 'قرقيرة', 'ظفر', 'أبو ياسين', 'كفر صقر',
       'الحصاينة', 'ميت غراب', 'الجلالية', 'السمارة', 'مجمع', 'ميت فارس',
       'الصلاحات', 'بنى عبيد'], dtype=object)

In [19]:
data['destination'].unique()

array(['دمياط', 'رأس البر', 'كفر الشيخ', 'قلين', 'الحامول', 'بيلا',
       'بلطيم', 'دسوق', 'فوه', 'مطوبس', 'دمنهور', 'أبو المطامير',
       'الدلنجات', 'شبراخيت', 'إيتاى البارود', 'مديرية التحرير',
       'مدينة بدر', 'كوم حمادة', 'طنطا', 'السنطة', 'كفر الزيات',
       'المحلة الكبرى', 'زفتى', 'شبين الكوم', 'تلا', 'نادر', 'الشهداء',
       'منوف', 'قويسنا', 'بركة السبع', 'الزقازيق', 'أبو حماد',
       'منيا القمح', 'بلبيس', 'ديرب نجم', 'فاقوس', 'أبو كبير', 'ههيا',
       'كفر صقر', 'الإبراهيمية', 'الحسينية', 'أولاد صقر', 'المنصورة',
       'دكرنس', 'السنبلاوين', 'شربين', 'المنزلة', 'منية النصر', 'بلقاس',
       'ميت غمر', 'جمصة', 'الإسكندرية', 'الإسكندرية (مكيف)', 'الفيوم',
       'يوسف الصديق', 'بنى سويف', 'الواسطى', 'المنيا', 'أسيوط', 'سوهاج',
       'الوادى الجديد', 'القرين', 'العاشر من رمضان', 'الصالحية الجديدة',
       'سمنود', 'بسيون', 'أجا', 'أبو حمص', 'حوش عيسى', 'رشيد', 'الرياض',
       'بنها', 'كفر شكر', 'المؤسسة', 'الشباب والعبور', 'العبور الجديدة',
       'الهرم', '6 اكتوبر', 'المستقبل', 'الشروق', 'العاصمة الإدارية',
       'التجمع الخامس', 'مدينتى', 'الرحاب', 'الحى العاشر', 'أبشواى',
       'قنا', 'ملوى', 'السويس', 'السويس (بيجو)', 'بورتو السخنة',
       'الإسماعيلية', 'الإسماعيلية (بيجو)', 'فايد', 'فايد (بيجو)',
       'القصاصين', 'القنطرة', 'التل الكبير', 'بورسعيد', 'بورسعيد (بيجو)',
       'الطور', 'نويبع', 'رأس سدر', 'العريش', 'العريش (بيجو)', 'رفح',
       'العلمين', 'العلمين (مكيف)', '6 اكتوبر (قديم)', 'كفر الدوار',
       'المنصورة الجدية', 'دمياط الجديدة', 'عبود', 'الزاوية الحمراء',
       'مسطرد', 'الدائرى', 'عزبة - مترو', 'طامية', 'سنورس', 'سنهور',
       'الصف', 'أطفيح', 'البرمبل', 'العبور ', 'المنيب', 'حلوان', 'المرج',
       'السلام', 'الفيوم (زراعى)', 'الفيوم (صحراوى)', 'شريف باشا', 'ناصر',
       'الزيتون', 'بنى عدى', 'إشمنت', 'الميمون', 'بنى حدير', 'دلاص',
       'طنسا الملق', 'طنسا بنى مالو', 'بنى قاسم', 'ببا', 'سدس الأمراء',
       'باروط', 'إهوة', 'الفشن', 'قنبش الحمراء', 'الحلابية',
       'تزمنت الشرقية', 'سمسطا', 'إهناسيا الخضراء', 'إهناسيا المدينة',
       'اللاهون', 'نعيم', 'طحا بوش', 'باها', 'المسيد الأبيض',
       'المدينة شرق النيل', 'العلالمة', 'الورشة', 'بياض العرب',
       'بنى سليمان', 'جزيرة أبو صالح', 'سنور', 'تل الناروز', 'بنى هارون',
       'بنى عفان', 'بنى بخيت', 'غياضة الغربية', 'شاويش', 'بلفيا', 'إبشنا',
       'دنديل', 'أبو صير الملق', 'بهبشين', 'السعادنة', 'دموشيا',
       'كوم أبو خلاد', 'قاى', 'الضباعنة', 'الملاحية', 'عزبة معارك',
       'الحاجر', 'اسكندر تل منصور', 'رياض باشا', 'معصرة نعسان',
       'عزبة على حمودة', 'السلطانى', 'البرانقة', 'منشأة عاصم', 'شوشة',
       'هربشنت', 'سراج', 'الشراهنة', 'طرشوب', 'أبو شربان', 'البرقى',
       'صفط رشين', 'بنى مؤمنة', 'المزرعة', 'دشطوط', 'عمار والزاوية',
       'لوبى المحيط', 'عزبة هوس', 'الشريف', 'الإمام', 'كفر ناصر',
       'عزبة نجيب', 'أبو عدس', 'غياضة', 'بنى ماضى', 'كفر منصور', 'اسكندر',
       'سدس البلد', 'برامل', 'بدهل', 'رزقة المشارقة', 'نزلة على كيلانى',
       'طحا البيشة', 'هلية', 'كوم الصعايدة', 'مغاغة', 'صفط الخرسا',
       'صفط العرفا', 'دلهانس', 'الجفادون', 'الجمهود', 'شنرا', 'منسابة',
       'اقفهص', 'نزلة اقفهص', 'بكرية', 'تلت', 'نزلة البرقى', 'الكنيسة',
       'صفط النور', 'بسفا', 'الفنت', 'منشأة عمر', 'صالح فريد', 'القضابى',
       'الفنت الغربية', 'الشقر', 'كفر درويش', 'ابسوج', 'نزلة حنا',
       'الزاوية الخضراء', 'بنى صالح', 'طلا', 'الشوبك', 'وش الباب',
       'براوة الوقف', 'البهسمون', 'ميانة', 'منهرو', 'النويرة',
       'دير براوة', 'البدينى', 'منشأة كساب', 'ننا', 'منشأة عبد الصمد',
       'بهنموة', 'ادراسية', 'شرهى', 'العواونة', 'المعصرة',
       'كوم الرمل البحرى', 'بنى هانى', 'سدمنت الجبل', 'طما فيوم',
       'كفر أبو شهبة', 'المشارقة وقلة', 'قلها', 'منشأة الأمراء',
       'الأنصار', 'منشأة الحج', 'منشأة طاهر', 'نزلة خلف', 'زكى فاضل',
       'العساكرة', 'الزاوية', 'نزلة الديب', 'عمار', 'منشأة أبو مليح',
       'بنى حلة', 'الشماشرجى', 'قفطان الشرقية', 'مصطفى آغا',
       'عزبة أبو حسانين', 'بنى محمد راشد', 'المحمودية', 'عزبة معوض',
       'الشنطور', 'دشاشة', 'الشيخ خطاب', 'كوم النور', 'الريغة البحرية',
       'عزبة نصر جمعة', 'كوم الرمل القبلى', 'القصبة', 'سربو',
       'قفطان الغربية', 'مازوره', 'الشيخ عابد', 'الأزهرى',
       'القرية الأولى', 'القرية الثانية ', 'القرية الثالثة',
       'كفر الجزيرة', 'عطف إفوة', 'إفوة', 'ميدوم', 'صفط الشرقية',
       'صفط الغربية', 'الحومة', 'قمن العروس', 'كفر أبيج', 'كوم ادريجه',
       'كفر بنى عتمان', 'انفسط', 'ونا القس', 'إبويط', 'كوم أبو راضى',
       'معصرة أبو صير', 'الديابة', 'أطواب', 'الرقة', 'القطورى', 'جرزا',
       'المتانيا', 'كفر عمار', 'العياط', 'فارسكور', 'ميت أبو غالب',
       'الإصلاح', 'كفر سليمان', 'الوسطانى', 'السوالم', 'كفر شحاتة',
       'كفر سعد البلد', 'الزهراء', 'العباسية', 'طلخا', 'كفر سعد',
       'الزرقا', 'كفر البطيخ', 'الروضة',
       'موقف دمياط الجديدة أسفل الكوبرى', 'البصارطة', 'عزبة البرج',
       'كفر الغاب', 'عزبة البط', 'القاهرة', 'موقف دمياط أسفل الكوبرى',
       'دمياط باب الحرس', 'أم الرضا', 'القاهرة (صحراوى)',
       'القاهرة (زراعى)', 'الجمالية', 'المطرية', 'ميت سلسيل',
       'دمياط (طريق المطرى)', 'بورسعيد ', 'القاهرة ', 'الطاهرى', 'النزل',
       'شرمساح', 'سيف الدين', 'السرو', 'عزبة الباز', 'تفتيش السرو',
       'الرحامنة', 'شرباص', 'الناصرية', 'كفرالعرب', 'الغنيمية',
       'كرم ورزوق', 'الطرحة', 'المؤسسة (الطريق الإقليمى)', 'السادات',
       'اسطنها', 'ابشيش', 'تلبنت اشيش', 'ميت الوسطى', 'ميت البيضا',
       'سنتريس', 'سمان', 'الخضرة', 'بير شمس', 'الغنامية', 'بى العرب',
       'كوم الضبع', 'شنوان', 'جروان', 'ميت عفيف', 'مشيرف',
       'كفر شبرا زنجى', 'سرس الليان', 'فيشا الصغرى', 'تلوانة',
       'كفر الباجور', 'كفر سنجلف', 'بهناى', 'كفر محمود', 'الكتامية',
       'أبو سنيط', 'القرنين', 'سبك الضحاك', 'مناوهلة', 'كفر مناوهلة',
       'كفر صناديد', 'القلشى', 'البندارية', 'ميت أبو الكوم', 'كفر عسكر',
       'زاوية بمم', 'طبلوها', 'كفر العرب', 'بمم', 'زنارة', 'الكمايشة',
       'كفر زرقان', 'قشطوخ', 'كفر بتبس', 'كفر السكرية', 'سماليج',
       'كفر الشيخ عبيد', 'كفر القلشى', 'كفر سماليج', 'شبرا بتوش', 'بابل',
       'طوخ دلكة', 'ميت الكرام', 'كفر العلوى', 'صفط الجدام', 'طنوب',
       'كفر ربيع', 'كفر الشرفا الغرب', 'كوم مازن', 'كمشيش', 'زرقان',
       'بروى', 'كفر جنزوز', 'طملاى', 'الطرانة', 'الأخماس', 'الخطاطبة',
       'الجيزة', 'المحور', 'النوبارية', 'العراقية', 'العامرية',
       'وادى النطرون', 'قرية عدنان المدنى', 'كود حمادة', 'أشمون',
       'المظلات (الطريق القديم)', 'المظلات (الطريق الحر)', 'مدينة السلام',
       'الباجور', 'عبود ', 'برهيم', 'بلمشط', 'الخمسين', 'جزى', 'صنصفط',
       'بهواش', 'ساقية المنقدى', 'سدود', 'رملة الأنجب', 'كمشوش',
       'منشأة سلطان', 'سنجرج', 'شما', 'كفر فيشا الكبرى', 'فيشا الكبرى',
       'شبرا بلولة', 'دمليج', 'دبركى', 'كفر داوود', 'تتا', 'كلية الهندسة',
       'زاوية رزين', 'كفر العشرى', 'شبشير طملاى', 'كفر السنابسة',
       'مركز بدر', 'معدية عبد العليم (مركز كوم حمادة)',
       'عبود (الطريق الإقليمى)', 'سروهيت', 'الزهور', 'مصطاى', 'الرمالى',
       'بنى غريان', 'أم خنان', 'كفر الأكرم', 'طه شبرا', 'كفر أبو الحسن',
       'كفر هلال', 'كفور الرمل', 'عرب الرمل', 'منشأة دملو', 'كفر إبهنس',
       'أجهور', 'أشليم', 'شرانيس', 'إبنهس', 'المنطقة الصناعية',
       'كفر المنشى', 'ميت بره', 'بجيرم', 'دمهوج', 'شبرا بخوم',
       'شبرا قبالة', 'منشية العرب', 'دنشواى', 'أبو كلس', 'دناصور',
       'بشتامى', 'زاوية البقلى', 'عمروس', 'إبشادى', 'كفر عشما', 'عشما',
       'سلامون', 'كفر الجلابطة', 'زاوية الناعورة', 'كفر دنشواى', 'شمياطس',
       'ساحل الجوابر', 'كفر الجمالة', 'دراجيل', 'كفر السولمية',
       'كفر الشبع', 'سرسموس', 'كفر سرسموس', 'البتانون', 'الطبرانى',
       'شبين الكوم (طريق القاصد)', 'شبين الكوم (طريق الدبايبة)', 'جنزور',
       'شنتنا الحجر', 'أبو مشهور', 'الشهيد فكرى', 'ميت فارس', 'كفر مليج',
       'الدبايبة', 'طنبشا', 'كفر عليم', 'كفر هورين', 'هورين', 'كفر نفرة',
       'الحلامشة', 'طوخ طنبشا', 'مليج', 'كفر الحمايدة', 'الجعفرية',
       'كفر المصيلحة', 'الراهب', 'الماى', 'منشأة شنوان', 'الدلاتون',
       'المصيلحة', 'ميت خلف', 'ميت مسعود', 'اصطبارى', 'شبرا خلفون',
       'زوير', 'سلكا', 'ميت الموز', 'ميت سراج', 'العجايزة', 'ميت خاقان',
       'كفر طنبدى', 'الكوم الأخضر', 'طنبدى', 'كفر البتانون', 'ميت موسى',
       'منشأة عصام', 'بخاتى ', 'طريق البتانون', 'شنوفة', 'دكما', 'بتبس',
       'سفاجا', 'الغردقة', 'شرم الشيخ', 'دهب ',
       'بركة السبع (طريق القاصد)', 'بركة السبع (طريق الدبايبة)',
       'المظلات', 'القناطر', 'دروة', 'النعناعية', 'أبو رقبة', 'كفر قورص',
       'مجريا', 'شنشور', 'سمادون', 'شعشاع', 'كفر الغريب', 'طهواى',
       'دلهمو', 'أبو عوالى', 'جريس', 'طليا', 'محلة سبك', 'البرانية',
       'الكوادى', 'كفر السيد', 'الخور', 'الحلواصى', 'مؤنسة', 'شوشاى',
       'بوهة شطانوف', 'ساقية أبو شعرة', 'كفر الحما', 'عزبة الفرعونية',
       'محلة الدمنة', 'بدواى', 'البارمون', 'كفر البرامون', 'البدالة',
       'الدنابيق', 'شبرا وبدين', 'الخيارية', 'كفر الأعجر', 'ديمشلت',
       'نقيطة', 'منية سندوب', 'برج النور', 'بلجاى', 'البقلية',
       'ميت الأكراد', 'دماص', 'شاوه', 'كود الدربى', 'تلبانة',
       'تمى الأمديد', 'بنى عبيد', 'ميت على', 'برق العز', 'طناح',
       'أويش الحجر', 'كفر الشنهاب', 'منية سمنود', 'نوسا البحر', 'نبروه',
       'بسنديلة', 'ديمره', 'أورمان', 'المنيل', 'كفور العرب',
       'كفر الأصالى', 'كفر ديمره', 'ميت زنقر', 'بطره', 'شرنقاش',
       'ميت عنتر', 'ميت الكرما', 'المنشية', 'سندوب', 'نوسا الغيط',
       'فيشابنا', 'ميت دمسيس', 'شبراويش', 'سماحة', 'الديرس',
       'ميت أبو الحارث', 'جراح', 'شنيسة', 'بقطارس', 'الدير', 'سنجيد',
       'ميت العامل', 'أخطاب', 'الغراقة ', 'ميت فضالة', 'ميت القرشى',
       'اتميدة', 'ميت محسن', 'سنتماى', 'أوليلة', 'إبيس البحيرة',
       'ميت العز', 'كفر النعيم', 'ميت ناجى', 'سرنجا', 'ميت أبو خالد',
       'ميت يعيش', 'هلا', 'بشلا', 'صهرجت', 'الدبونية', 'كفور البهايتة',
       'ميت الفرماوى', 'دنديط', 'كفر بهيدة', 'سنفا', 'كفر النعمان',
       'كفر سرنجا', 'التحرير', 'نجير', 'محلة دمنة', 'ميت طريف', 'الشركة',
       'منشأة عبد الرحمن', 'الصلاحات', 'أشمون الرمان', 'حادوس',
       'اليوسيفية', 'ظفر', 'ميت عدلان', 'الكردى', 'ديرب الخضر',
       'ميت تمامة', 'البجلات', 'الجنينة', 'الإتحاد', 'صان', 'مصر الجديدة',
       'الإسكندرية الجديدة', 'ميت مرجا سلسيل', 'البصراط', 'كفور الجمالية',
       'كفر علام', 'النسايمة', 'الأحمدية', 'الفروسات', 'العزيزة',
       'العامرة', 'المواجد', 'المنزلة الجديدة', 'الحوتة', 'ميت عاصم',
       'العصافرة', 'بهوت', 'الطيبة', 'تيرة', 'درين', 'كفر الأبحر',
       'ميت عباد', 'بانوب', 'نشا', 'طنيخ', 'الجزاير', 'الملعب',
       'الدمايرة', 'جميانة', 'وزير', 'زقلمة', 'القطنة', 'دملاش', 'قراش',
       'أبو دشيشة', 'الكردود', 'أبو طه', 'الهلالى', 'قلابشو', 'جالية',
       'الجرايدة', 'شرقية المعصرة', 'الستامونى', 'الخلالة', 'البنزينة',
       'حفير 57', 'الشوامى', 'بطرة', 'تفتيش كفر سعد', 'أم الرزق',
       'الصبرية', 'رأس الخليج', 'الأطرش', 'الوكالة', 'ترعة غنيم',
       'العيادية', 'أبو جلال', 'بنيامين', 'الدبوسى', 'الشناوى', 'الضهرية',
       'دنجواى', 'العوضية', 'بساط', 'البرامون', 'الحصص', 'منشأة النصر',
       'كفر شريف', 'أبو زاهر', 'كفر الترعة', 'كفر الحطبة', 'ديسط',
       'البشينى', 'البلامون', 'قرقيرة', 'غزالة', 'صدقا', 'أبو ياسين',
       'كفر عزام', 'الجلالية', 'كفر غنام', 'صافور', 'طوخ الأقلام', 'نوب',
       'الزهايرة', 'الحصاينة', 'ديو الوسطى', 'طنبول', 'ميت غراب',
       'شبراهور', 'الأورمان', 'شبرا سندى', 'برقين', 'برهمتوش',
       'أبو قراميط', 'بشمس', 'البكارية', 'منشأة أدهم', 'كفر قنصوة',
       'كفر الروك', 'المخزن', 'التمد', 'طنبارة', 'كفر الأمير', 'القاسمى',
       'أبو الصير', 'السمارة', 'أبو داوود', 'المقاطعة', 'الربع', 'البيضا',
       'تاج العز', 'المبهى', 'منشأة السلام', 'ميت صبرى أبو علم',
       'الحدادة', 'غازى مصبح', 'أبو المعاطى الباز', 'طلمبا بنى عبيد'],
      dtype=object)

In [20]:
data['destination']=data['destination'].str.strip()
data['destination'].unique()

array(['دمياط', 'رأس البر', 'كفر الشيخ', 'قلين', 'الحامول', 'بيلا',
       'بلطيم', 'دسوق', 'فوه', 'مطوبس', 'دمنهور', 'أبو المطامير',
       'الدلنجات', 'شبراخيت', 'إيتاى البارود', 'مديرية التحرير',
       'مدينة بدر', 'كوم حمادة', 'طنطا', 'السنطة', 'كفر الزيات',
       'المحلة الكبرى', 'زفتى', 'شبين الكوم', 'تلا', 'نادر', 'الشهداء',
       'منوف', 'قويسنا', 'بركة السبع', 'الزقازيق', 'أبو حماد',
       'منيا القمح', 'بلبيس', 'ديرب نجم', 'فاقوس', 'أبو كبير', 'ههيا',
       'كفر صقر', 'الإبراهيمية', 'الحسينية', 'أولاد صقر', 'المنصورة',
       'دكرنس', 'السنبلاوين', 'شربين', 'المنزلة', 'منية النصر', 'بلقاس',
       'ميت غمر', 'جمصة', 'الإسكندرية', 'الإسكندرية (مكيف)', 'الفيوم',
       'يوسف الصديق', 'بنى سويف', 'الواسطى', 'المنيا', 'أسيوط', 'سوهاج',
       'الوادى الجديد', 'القرين', 'العاشر من رمضان', 'الصالحية الجديدة',
       'سمنود', 'بسيون', 'أجا', 'أبو حمص', 'حوش عيسى', 'رشيد', 'الرياض',
       'بنها', 'كفر شكر', 'المؤسسة', 'الشباب والعبور', 'العبور الجديدة',
       'الهرم', '6 اكتوبر', 'المستقبل', 'الشروق', 'العاصمة الإدارية',
       'التجمع الخامس', 'مدينتى', 'الرحاب', 'الحى العاشر', 'أبشواى',
       'قنا', 'ملوى', 'السويس', 'السويس (بيجو)', 'بورتو السخنة',
       'الإسماعيلية', 'الإسماعيلية (بيجو)', 'فايد', 'فايد (بيجو)',
       'القصاصين', 'القنطرة', 'التل الكبير', 'بورسعيد', 'بورسعيد (بيجو)',
       'الطور', 'نويبع', 'رأس سدر', 'العريش', 'العريش (بيجو)', 'رفح',
       'العلمين', 'العلمين (مكيف)', '6 اكتوبر (قديم)', 'كفر الدوار',
       'المنصورة الجدية', 'دمياط الجديدة', 'عبود', 'الزاوية الحمراء',
       'مسطرد', 'الدائرى', 'عزبة - مترو', 'طامية', 'سنورس', 'سنهور',
       'الصف', 'أطفيح', 'البرمبل', 'العبور', 'المنيب', 'حلوان', 'المرج',
       'السلام', 'الفيوم (زراعى)', 'الفيوم (صحراوى)', 'شريف باشا', 'ناصر',
       'الزيتون', 'بنى عدى', 'إشمنت', 'الميمون', 'بنى حدير', 'دلاص',
       'طنسا الملق', 'طنسا بنى مالو', 'بنى قاسم', 'ببا', 'سدس الأمراء',
       'باروط', 'إهوة', 'الفشن', 'قنبش الحمراء', 'الحلابية',
       'تزمنت الشرقية', 'سمسطا', 'إهناسيا الخضراء', 'إهناسيا المدينة',
       'اللاهون', 'نعيم', 'طحا بوش', 'باها', 'المسيد الأبيض',
       'المدينة شرق النيل', 'العلالمة', 'الورشة', 'بياض العرب',
       'بنى سليمان', 'جزيرة أبو صالح', 'سنور', 'تل الناروز', 'بنى هارون',
       'بنى عفان', 'بنى بخيت', 'غياضة الغربية', 'شاويش', 'بلفيا', 'إبشنا',
       'دنديل', 'أبو صير الملق', 'بهبشين', 'السعادنة', 'دموشيا',
       'كوم أبو خلاد', 'قاى', 'الضباعنة', 'الملاحية', 'عزبة معارك',
       'الحاجر', 'اسكندر تل منصور', 'رياض باشا', 'معصرة نعسان',
       'عزبة على حمودة', 'السلطانى', 'البرانقة', 'منشأة عاصم', 'شوشة',
       'هربشنت', 'سراج', 'الشراهنة', 'طرشوب', 'أبو شربان', 'البرقى',
       'صفط رشين', 'بنى مؤمنة', 'المزرعة', 'دشطوط', 'عمار والزاوية',
       'لوبى المحيط', 'عزبة هوس', 'الشريف', 'الإمام', 'كفر ناصر',
       'عزبة نجيب', 'أبو عدس', 'غياضة', 'بنى ماضى', 'كفر منصور', 'اسكندر',
       'سدس البلد', 'برامل', 'بدهل', 'رزقة المشارقة', 'نزلة على كيلانى',
       'طحا البيشة', 'هلية', 'كوم الصعايدة', 'مغاغة', 'صفط الخرسا',
       'صفط العرفا', 'دلهانس', 'الجفادون', 'الجمهود', 'شنرا', 'منسابة',
       'اقفهص', 'نزلة اقفهص', 'بكرية', 'تلت', 'نزلة البرقى', 'الكنيسة',
       'صفط النور', 'بسفا', 'الفنت', 'منشأة عمر', 'صالح فريد', 'القضابى',
       'الفنت الغربية', 'الشقر', 'كفر درويش', 'ابسوج', 'نزلة حنا',
       'الزاوية الخضراء', 'بنى صالح', 'طلا', 'الشوبك', 'وش الباب',
       'براوة الوقف', 'البهسمون', 'ميانة', 'منهرو', 'النويرة',
       'دير براوة', 'البدينى', 'منشأة كساب', 'ننا', 'منشأة عبد الصمد',
       'بهنموة', 'ادراسية', 'شرهى', 'العواونة', 'المعصرة',
       'كوم الرمل البحرى', 'بنى هانى', 'سدمنت الجبل', 'طما فيوم',
       'كفر أبو شهبة', 'المشارقة وقلة', 'قلها', 'منشأة الأمراء',
       'الأنصار', 'منشأة الحج', 'منشأة طاهر', 'نزلة خلف', 'زكى فاضل',
       'العساكرة', 'الزاوية', 'نزلة الديب', 'عمار', 'منشأة أبو مليح',
       'بنى حلة', 'الشماشرجى', 'قفطان الشرقية', 'مصطفى آغا',
       'عزبة أبو حسانين', 'بنى محمد راشد', 'المحمودية', 'عزبة معوض',
       'الشنطور', 'دشاشة', 'الشيخ خطاب', 'كوم النور', 'الريغة البحرية',
       'عزبة نصر جمعة', 'كوم الرمل القبلى', 'القصبة', 'سربو',
       'قفطان الغربية', 'مازوره', 'الشيخ عابد', 'الأزهرى',
       'القرية الأولى', 'القرية الثانية', 'القرية الثالثة', 'كفر الجزيرة',
       'عطف إفوة', 'إفوة', 'ميدوم', 'صفط الشرقية', 'صفط الغربية',
       'الحومة', 'قمن العروس', 'كفر أبيج', 'كوم ادريجه', 'كفر بنى عتمان',
       'انفسط', 'ونا القس', 'إبويط', 'كوم أبو راضى', 'معصرة أبو صير',
       'الديابة', 'أطواب', 'الرقة', 'القطورى', 'جرزا', 'المتانيا',
       'كفر عمار', 'العياط', 'فارسكور', 'ميت أبو غالب', 'الإصلاح',
       'كفر سليمان', 'الوسطانى', 'السوالم', 'كفر شحاتة', 'كفر سعد البلد',
       'الزهراء', 'العباسية', 'طلخا', 'كفر سعد', 'الزرقا', 'كفر البطيخ',
       'الروضة', 'موقف دمياط الجديدة أسفل الكوبرى', 'البصارطة',
       'عزبة البرج', 'كفر الغاب', 'عزبة البط', 'القاهرة',
       'موقف دمياط أسفل الكوبرى', 'دمياط باب الحرس', 'أم الرضا',
       'القاهرة (صحراوى)', 'القاهرة (زراعى)', 'الجمالية', 'المطرية',
       'ميت سلسيل', 'دمياط (طريق المطرى)', 'الطاهرى', 'النزل', 'شرمساح',
       'سيف الدين', 'السرو', 'عزبة الباز', 'تفتيش السرو', 'الرحامنة',
       'شرباص', 'الناصرية', 'كفرالعرب', 'الغنيمية', 'كرم ورزوق', 'الطرحة',
       'المؤسسة (الطريق الإقليمى)', 'السادات', 'اسطنها', 'ابشيش',
       'تلبنت اشيش', 'ميت الوسطى', 'ميت البيضا', 'سنتريس', 'سمان',
       'الخضرة', 'بير شمس', 'الغنامية', 'بى العرب', 'كوم الضبع', 'شنوان',
       'جروان', 'ميت عفيف', 'مشيرف', 'كفر شبرا زنجى', 'سرس الليان',
       'فيشا الصغرى', 'تلوانة', 'كفر الباجور', 'كفر سنجلف', 'بهناى',
       'كفر محمود', 'الكتامية', 'أبو سنيط', 'القرنين', 'سبك الضحاك',
       'مناوهلة', 'كفر مناوهلة', 'كفر صناديد', 'القلشى', 'البندارية',
       'ميت أبو الكوم', 'كفر عسكر', 'زاوية بمم', 'طبلوها', 'كفر العرب',
       'بمم', 'زنارة', 'الكمايشة', 'كفر زرقان', 'قشطوخ', 'كفر بتبس',
       'كفر السكرية', 'سماليج', 'كفر الشيخ عبيد', 'كفر القلشى',
       'كفر سماليج', 'شبرا بتوش', 'بابل', 'طوخ دلكة', 'ميت الكرام',
       'كفر العلوى', 'صفط الجدام', 'طنوب', 'كفر ربيع', 'كفر الشرفا الغرب',
       'كوم مازن', 'كمشيش', 'زرقان', 'بروى', 'كفر جنزوز', 'طملاى',
       'الطرانة', 'الأخماس', 'الخطاطبة', 'الجيزة', 'المحور', 'النوبارية',
       'العراقية', 'العامرية', 'وادى النطرون', 'قرية عدنان المدنى',
       'كود حمادة', 'أشمون', 'المظلات (الطريق القديم)',
       'المظلات (الطريق الحر)', 'مدينة السلام', 'الباجور', 'برهيم',
       'بلمشط', 'الخمسين', 'جزى', 'صنصفط', 'بهواش', 'ساقية المنقدى',
       'سدود', 'رملة الأنجب', 'كمشوش', 'منشأة سلطان', 'سنجرج', 'شما',
       'كفر فيشا الكبرى', 'فيشا الكبرى', 'شبرا بلولة', 'دمليج', 'دبركى',
       'كفر داوود', 'تتا', 'كلية الهندسة', 'زاوية رزين', 'كفر العشرى',
       'شبشير طملاى', 'كفر السنابسة', 'مركز بدر',
       'معدية عبد العليم (مركز كوم حمادة)', 'عبود (الطريق الإقليمى)',
       'سروهيت', 'الزهور', 'مصطاى', 'الرمالى', 'بنى غريان', 'أم خنان',
       'كفر الأكرم', 'طه شبرا', 'كفر أبو الحسن', 'كفر هلال', 'كفور الرمل',
       'عرب الرمل', 'منشأة دملو', 'كفر إبهنس', 'أجهور', 'أشليم', 'شرانيس',
       'إبنهس', 'المنطقة الصناعية', 'كفر المنشى', 'ميت بره', 'بجيرم',
       'دمهوج', 'شبرا بخوم', 'شبرا قبالة', 'منشية العرب', 'دنشواى',
       'أبو كلس', 'دناصور', 'بشتامى', 'زاوية البقلى', 'عمروس', 'إبشادى',
       'كفر عشما', 'عشما', 'سلامون', 'كفر الجلابطة', 'زاوية الناعورة',
       'كفر دنشواى', 'شمياطس', 'ساحل الجوابر', 'كفر الجمالة', 'دراجيل',
       'كفر السولمية', 'كفر الشبع', 'سرسموس', 'كفر سرسموس', 'البتانون',
       'الطبرانى', 'شبين الكوم (طريق القاصد)',
       'شبين الكوم (طريق الدبايبة)', 'جنزور', 'شنتنا الحجر', 'أبو مشهور',
       'الشهيد فكرى', 'ميت فارس', 'كفر مليج', 'الدبايبة', 'طنبشا',
       'كفر عليم', 'كفر هورين', 'هورين', 'كفر نفرة', 'الحلامشة',
       'طوخ طنبشا', 'مليج', 'كفر الحمايدة', 'الجعفرية', 'كفر المصيلحة',
       'الراهب', 'الماى', 'منشأة شنوان', 'الدلاتون', 'المصيلحة',
       'ميت خلف', 'ميت مسعود', 'اصطبارى', 'شبرا خلفون', 'زوير', 'سلكا',
       'ميت الموز', 'ميت سراج', 'العجايزة', 'ميت خاقان', 'كفر طنبدى',
       'الكوم الأخضر', 'طنبدى', 'كفر البتانون', 'ميت موسى', 'منشأة عصام',
       'بخاتى', 'طريق البتانون', 'شنوفة', 'دكما', 'بتبس', 'سفاجا',
       'الغردقة', 'شرم الشيخ', 'دهب', 'بركة السبع (طريق القاصد)',
       'بركة السبع (طريق الدبايبة)', 'المظلات', 'القناطر', 'دروة',
       'النعناعية', 'أبو رقبة', 'كفر قورص', 'مجريا', 'شنشور', 'سمادون',
       'شعشاع', 'كفر الغريب', 'طهواى', 'دلهمو', 'أبو عوالى', 'جريس',
       'طليا', 'محلة سبك', 'البرانية', 'الكوادى', 'كفر السيد', 'الخور',
       'الحلواصى', 'مؤنسة', 'شوشاى', 'بوهة شطانوف', 'ساقية أبو شعرة',
       'كفر الحما', 'عزبة الفرعونية', 'محلة الدمنة', 'بدواى', 'البارمون',
       'كفر البرامون', 'البدالة', 'الدنابيق', 'شبرا وبدين', 'الخيارية',
       'كفر الأعجر', 'ديمشلت', 'نقيطة', 'منية سندوب', 'برج النور',
       'بلجاى', 'البقلية', 'ميت الأكراد', 'دماص', 'شاوه', 'كود الدربى',
       'تلبانة', 'تمى الأمديد', 'بنى عبيد', 'ميت على', 'برق العز', 'طناح',
       'أويش الحجر', 'كفر الشنهاب', 'منية سمنود', 'نوسا البحر', 'نبروه',
       'بسنديلة', 'ديمره', 'أورمان', 'المنيل', 'كفور العرب',
       'كفر الأصالى', 'كفر ديمره', 'ميت زنقر', 'بطره', 'شرنقاش',
       'ميت عنتر', 'ميت الكرما', 'المنشية', 'سندوب', 'نوسا الغيط',
       'فيشابنا', 'ميت دمسيس', 'شبراويش', 'سماحة', 'الديرس',
       'ميت أبو الحارث', 'جراح', 'شنيسة', 'بقطارس', 'الدير', 'سنجيد',
       'ميت العامل', 'أخطاب', 'الغراقة', 'ميت فضالة', 'ميت القرشى',
       'اتميدة', 'ميت محسن', 'سنتماى', 'أوليلة', 'إبيس البحيرة',
       'ميت العز', 'كفر النعيم', 'ميت ناجى', 'سرنجا', 'ميت أبو خالد',
       'ميت يعيش', 'هلا', 'بشلا', 'صهرجت', 'الدبونية', 'كفور البهايتة',
       'ميت الفرماوى', 'دنديط', 'كفر بهيدة', 'سنفا', 'كفر النعمان',
       'كفر سرنجا', 'التحرير', 'نجير', 'محلة دمنة', 'ميت طريف', 'الشركة',
       'منشأة عبد الرحمن', 'الصلاحات', 'أشمون الرمان', 'حادوس',
       'اليوسيفية', 'ظفر', 'ميت عدلان', 'الكردى', 'ديرب الخضر',
       'ميت تمامة', 'البجلات', 'الجنينة', 'الإتحاد', 'صان', 'مصر الجديدة',
       'الإسكندرية الجديدة', 'ميت مرجا سلسيل', 'البصراط', 'كفور الجمالية',
       'كفر علام', 'النسايمة', 'الأحمدية', 'الفروسات', 'العزيزة',
       'العامرة', 'المواجد', 'المنزلة الجديدة', 'الحوتة', 'ميت عاصم',
       'العصافرة', 'بهوت', 'الطيبة', 'تيرة', 'درين', 'كفر الأبحر',
       'ميت عباد', 'بانوب', 'نشا', 'طنيخ', 'الجزاير', 'الملعب',
       'الدمايرة', 'جميانة', 'وزير', 'زقلمة', 'القطنة', 'دملاش', 'قراش',
       'أبو دشيشة', 'الكردود', 'أبو طه', 'الهلالى', 'قلابشو', 'جالية',
       'الجرايدة', 'شرقية المعصرة', 'الستامونى', 'الخلالة', 'البنزينة',
       'حفير 57', 'الشوامى', 'بطرة', 'تفتيش كفر سعد', 'أم الرزق',
       'الصبرية', 'رأس الخليج', 'الأطرش', 'الوكالة', 'ترعة غنيم',
       'العيادية', 'أبو جلال', 'بنيامين', 'الدبوسى', 'الشناوى', 'الضهرية',
       'دنجواى', 'العوضية', 'بساط', 'البرامون', 'الحصص', 'منشأة النصر',
       'كفر شريف', 'أبو زاهر', 'كفر الترعة', 'كفر الحطبة', 'ديسط',
       'البشينى', 'البلامون', 'قرقيرة', 'غزالة', 'صدقا', 'أبو ياسين',
       'كفر عزام', 'الجلالية', 'كفر غنام', 'صافور', 'طوخ الأقلام', 'نوب',
       'الزهايرة', 'الحصاينة', 'ديو الوسطى', 'طنبول', 'ميت غراب',
       'شبراهور', 'الأورمان', 'شبرا سندى', 'برقين', 'برهمتوش',
       'أبو قراميط', 'بشمس', 'البكارية', 'منشأة أدهم', 'كفر قنصوة',
       'كفر الروك', 'المخزن', 'التمد', 'طنبارة', 'كفر الأمير', 'القاسمى',
       'أبو الصير', 'السمارة', 'أبو داوود', 'المقاطعة', 'الربع', 'البيضا',
       'تاج العز', 'المبهى', 'منشأة السلام', 'ميت صبرى أبو علم',
       'الحدادة', 'غازى مصبح', 'أبو المعاطى الباز', 'طلمبا بنى عبيد'],
      dtype=object)

In [21]:
data[data['destination']=='طلمبا بنى عبيد']['destination']='طلمبات بنى عبيد'
data['destination'].unique()

C:\Users\Dell\AppData\Local\Temp\ipykernel_4412\781952071.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[data['destination']=='طلمبا بنى عبيد']['destination']='طلمبات بنى عبيد'

array(['دمياط', 'رأس البر', 'كفر الشيخ', 'قلين', 'الحامول', 'بيلا',
       'بلطيم', 'دسوق', 'فوه', 'مطوبس', 'دمنهور', 'أبو المطامير',
       'الدلنجات', 'شبراخيت', 'إيتاى البارود', 'مديرية التحرير',
       'مدينة بدر', 'كوم حمادة', 'طنطا', 'السنطة', 'كفر الزيات',
       'المحلة الكبرى', 'زفتى', 'شبين الكوم', 'تلا', 'نادر', 'الشهداء',
       'منوف', 'قويسنا', 'بركة السبع', 'الزقازيق', 'أبو حماد',
       'منيا القمح', 'بلبيس', 'ديرب نجم', 'فاقوس', 'أبو كبير', 'ههيا',
       'كفر صقر', 'الإبراهيمية', 'الحسينية', 'أولاد صقر', 'المنصورة',
       'دكرنس', 'السنبلاوين', 'شربين', 'المنزلة', 'منية النصر', 'بلقاس',
       'ميت غمر', 'جمصة', 'الإسكندرية', 'الإسكندرية (مكيف)', 'الفيوم',
       'يوسف الصديق', 'بنى سويف', 'الواسطى', 'المنيا', 'أسيوط', 'سوهاج',
       'الوادى الجديد', 'القرين', 'العاشر من رمضان', 'الصالحية الجديدة',
       'سمنود', 'بسيون', 'أجا', 'أبو حمص', 'حوش عيسى', 'رشيد', 'الرياض',
       'بنها', 'كفر شكر', 'المؤسسة', 'الشباب والعبور', 'العبور الجديدة',
       'الهرم', '6 اكتوبر', 'المستقبل', 'الشروق', 'العاصمة الإدارية',
       'التجمع الخامس', 'مدينتى', 'الرحاب', 'الحى العاشر', 'أبشواى',
       'قنا', 'ملوى', 'السويس', 'السويس (بيجو)', 'بورتو السخنة',
       'الإسماعيلية', 'الإسماعيلية (بيجو)', 'فايد', 'فايد (بيجو)',
       'القصاصين', 'القنطرة', 'التل الكبير', 'بورسعيد', 'بورسعيد (بيجو)',
       'الطور', 'نويبع', 'رأس سدر', 'العريش', 'العريش (بيجو)', 'رفح',
       'العلمين', 'العلمين (مكيف)', '6 اكتوبر (قديم)', 'كفر الدوار',
       'المنصورة الجدية', 'دمياط الجديدة', 'عبود', 'الزاوية الحمراء',
       'مسطرد', 'الدائرى', 'عزبة - مترو', 'طامية', 'سنورس', 'سنهور',
       'الصف', 'أطفيح', 'البرمبل', 'العبور', 'المنيب', 'حلوان', 'المرج',
       'السلام', 'الفيوم (زراعى)', 'الفيوم (صحراوى)', 'شريف باشا', 'ناصر',
       'الزيتون', 'بنى عدى', 'إشمنت', 'الميمون', 'بنى حدير', 'دلاص',
       'طنسا الملق', 'طنسا بنى مالو', 'بنى قاسم', 'ببا', 'سدس الأمراء',
       'باروط', 'إهوة', 'الفشن', 'قنبش الحمراء', 'الحلابية',
       'تزمنت الشرقية', 'سمسطا', 'إهناسيا الخضراء', 'إهناسيا المدينة',
       'اللاهون', 'نعيم', 'طحا بوش', 'باها', 'المسيد الأبيض',
       'المدينة شرق النيل', 'العلالمة', 'الورشة', 'بياض العرب',
       'بنى سليمان', 'جزيرة أبو صالح', 'سنور', 'تل الناروز', 'بنى هارون',
       'بنى عفان', 'بنى بخيت', 'غياضة الغربية', 'شاويش', 'بلفيا', 'إبشنا',
       'دنديل', 'أبو صير الملق', 'بهبشين', 'السعادنة', 'دموشيا',
       'كوم أبو خلاد', 'قاى', 'الضباعنة', 'الملاحية', 'عزبة معارك',
       'الحاجر', 'اسكندر تل منصور', 'رياض باشا', 'معصرة نعسان',
       'عزبة على حمودة', 'السلطانى', 'البرانقة', 'منشأة عاصم', 'شوشة',
       'هربشنت', 'سراج', 'الشراهنة', 'طرشوب', 'أبو شربان', 'البرقى',
       'صفط رشين', 'بنى مؤمنة', 'المزرعة', 'دشطوط', 'عمار والزاوية',
       'لوبى المحيط', 'عزبة هوس', 'الشريف', 'الإمام', 'كفر ناصر',
       'عزبة نجيب', 'أبو عدس', 'غياضة', 'بنى ماضى', 'كفر منصور', 'اسكندر',
       'سدس البلد', 'برامل', 'بدهل', 'رزقة المشارقة', 'نزلة على كيلانى',
       'طحا البيشة', 'هلية', 'كوم الصعايدة', 'مغاغة', 'صفط الخرسا',
       'صفط العرفا', 'دلهانس', 'الجفادون', 'الجمهود', 'شنرا', 'منسابة',
       'اقفهص', 'نزلة اقفهص', 'بكرية', 'تلت', 'نزلة البرقى', 'الكنيسة',
       'صفط النور', 'بسفا', 'الفنت', 'منشأة عمر', 'صالح فريد', 'القضابى',
       'الفنت الغربية', 'الشقر', 'كفر درويش', 'ابسوج', 'نزلة حنا',
       'الزاوية الخضراء', 'بنى صالح', 'طلا', 'الشوبك', 'وش الباب',
       'براوة الوقف', 'البهسمون', 'ميانة', 'منهرو', 'النويرة',
       'دير براوة', 'البدينى', 'منشأة كساب', 'ننا', 'منشأة عبد الصمد',
       'بهنموة', 'ادراسية', 'شرهى', 'العواونة', 'المعصرة',
       'كوم الرمل البحرى', 'بنى هانى', 'سدمنت الجبل', 'طما فيوم',
       'كفر أبو شهبة', 'المشارقة وقلة', 'قلها', 'منشأة الأمراء',
       'الأنصار', 'منشأة الحج', 'منشأة طاهر', 'نزلة خلف', 'زكى فاضل',
       'العساكرة', 'الزاوية', 'نزلة الديب', 'عمار', 'منشأة أبو مليح',
       'بنى حلة', 'الشماشرجى', 'قفطان الشرقية', 'مصطفى آغا',
       'عزبة أبو حسانين', 'بنى محمد راشد', 'المحمودية', 'عزبة معوض',
       'الشنطور', 'دشاشة', 'الشيخ خطاب', 'كوم النور', 'الريغة البحرية',
       'عزبة نصر جمعة', 'كوم الرمل القبلى', 'القصبة', 'سربو',
       'قفطان الغربية', 'مازوره', 'الشيخ عابد', 'الأزهرى',
       'القرية الأولى', 'القرية الثانية', 'القرية الثالثة', 'كفر الجزيرة',
       'عطف إفوة', 'إفوة', 'ميدوم', 'صفط الشرقية', 'صفط الغربية',
       'الحومة', 'قمن العروس', 'كفر أبيج', 'كوم ادريجه', 'كفر بنى عتمان',
       'انفسط', 'ونا القس', 'إبويط', 'كوم أبو راضى', 'معصرة أبو صير',
       'الديابة', 'أطواب', 'الرقة', 'القطورى', 'جرزا', 'المتانيا',
       'كفر عمار', 'العياط', 'فارسكور', 'ميت أبو غالب', 'الإصلاح',
       'كفر سليمان', 'الوسطانى', 'السوالم', 'كفر شحاتة', 'كفر سعد البلد',
       'الزهراء', 'العباسية', 'طلخا', 'كفر سعد', 'الزرقا', 'كفر البطيخ',
       'الروضة', 'موقف دمياط الجديدة أسفل الكوبرى', 'البصارطة',
       'عزبة البرج', 'كفر الغاب', 'عزبة البط', 'القاهرة',
       'موقف دمياط أسفل الكوبرى', 'دمياط باب الحرس', 'أم الرضا',
       'القاهرة (صحراوى)', 'القاهرة (زراعى)', 'الجمالية', 'المطرية',
       'ميت سلسيل', 'دمياط (طريق المطرى)', 'الطاهرى', 'النزل', 'شرمساح',
       'سيف الدين', 'السرو', 'عزبة الباز', 'تفتيش السرو', 'الرحامنة',
       'شرباص', 'الناصرية', 'كفرالعرب', 'الغنيمية', 'كرم ورزوق', 'الطرحة',
       'المؤسسة (الطريق الإقليمى)', 'السادات', 'اسطنها', 'ابشيش',
       'تلبنت اشيش', 'ميت الوسطى', 'ميت البيضا', 'سنتريس', 'سمان',
       'الخضرة', 'بير شمس', 'الغنامية', 'بى العرب', 'كوم الضبع', 'شنوان',
       'جروان', 'ميت عفيف', 'مشيرف', 'كفر شبرا زنجى', 'سرس الليان',
       'فيشا الصغرى', 'تلوانة', 'كفر الباجور', 'كفر سنجلف', 'بهناى',
       'كفر محمود', 'الكتامية', 'أبو سنيط', 'القرنين', 'سبك الضحاك',
       'مناوهلة', 'كفر مناوهلة', 'كفر صناديد', 'القلشى', 'البندارية',
       'ميت أبو الكوم', 'كفر عسكر', 'زاوية بمم', 'طبلوها', 'كفر العرب',
       'بمم', 'زنارة', 'الكمايشة', 'كفر زرقان', 'قشطوخ', 'كفر بتبس',
       'كفر السكرية', 'سماليج', 'كفر الشيخ عبيد', 'كفر القلشى',
       'كفر سماليج', 'شبرا بتوش', 'بابل', 'طوخ دلكة', 'ميت الكرام',
       'كفر العلوى', 'صفط الجدام', 'طنوب', 'كفر ربيع', 'كفر الشرفا الغرب',
       'كوم مازن', 'كمشيش', 'زرقان', 'بروى', 'كفر جنزوز', 'طملاى',
       'الطرانة', 'الأخماس', 'الخطاطبة', 'الجيزة', 'المحور', 'النوبارية',
       'العراقية', 'العامرية', 'وادى النطرون', 'قرية عدنان المدنى',
       'كود حمادة', 'أشمون', 'المظلات (الطريق القديم)',
       'المظلات (الطريق الحر)', 'مدينة السلام', 'الباجور', 'برهيم',
       'بلمشط', 'الخمسين', 'جزى', 'صنصفط', 'بهواش', 'ساقية المنقدى',
       'سدود', 'رملة الأنجب', 'كمشوش', 'منشأة سلطان', 'سنجرج', 'شما',
       'كفر فيشا الكبرى', 'فيشا الكبرى', 'شبرا بلولة', 'دمليج', 'دبركى',
       'كفر داوود', 'تتا', 'كلية الهندسة', 'زاوية رزين', 'كفر العشرى',
       'شبشير طملاى', 'كفر السنابسة', 'مركز بدر',
       'معدية عبد العليم (مركز كوم حمادة)', 'عبود (الطريق الإقليمى)',
       'سروهيت', 'الزهور', 'مصطاى', 'الرمالى', 'بنى غريان', 'أم خنان',
       'كفر الأكرم', 'طه شبرا', 'كفر أبو الحسن', 'كفر هلال', 'كفور الرمل',
       'عرب الرمل', 'منشأة دملو', 'كفر إبهنس', 'أجهور', 'أشليم', 'شرانيس',
       'إبنهس', 'المنطقة الصناعية', 'كفر المنشى', 'ميت بره', 'بجيرم',
       'دمهوج', 'شبرا بخوم', 'شبرا قبالة', 'منشية العرب', 'دنشواى',
       'أبو كلس', 'دناصور', 'بشتامى', 'زاوية البقلى', 'عمروس', 'إبشادى',
       'كفر عشما', 'عشما', 'سلامون', 'كفر الجلابطة', 'زاوية الناعورة',
       'كفر دنشواى', 'شمياطس', 'ساحل الجوابر', 'كفر الجمالة', 'دراجيل',
       'كفر السولمية', 'كفر الشبع', 'سرسموس', 'كفر سرسموس', 'البتانون',
       'الطبرانى', 'شبين الكوم (طريق القاصد)',
       'شبين الكوم (طريق الدبايبة)', 'جنزور', 'شنتنا الحجر', 'أبو مشهور',
       'الشهيد فكرى', 'ميت فارس', 'كفر مليج', 'الدبايبة', 'طنبشا',
       'كفر عليم', 'كفر هورين', 'هورين', 'كفر نفرة', 'الحلامشة',
       'طوخ طنبشا', 'مليج', 'كفر الحمايدة', 'الجعفرية', 'كفر المصيلحة',
       'الراهب', 'الماى', 'منشأة شنوان', 'الدلاتون', 'المصيلحة',
       'ميت خلف', 'ميت مسعود', 'اصطبارى', 'شبرا خلفون', 'زوير', 'سلكا',
       'ميت الموز', 'ميت سراج', 'العجايزة', 'ميت خاقان', 'كفر طنبدى',
       'الكوم الأخضر', 'طنبدى', 'كفر البتانون', 'ميت موسى', 'منشأة عصام',
       'بخاتى', 'طريق البتانون', 'شنوفة', 'دكما', 'بتبس', 'سفاجا',
       'الغردقة', 'شرم الشيخ', 'دهب', 'بركة السبع (طريق القاصد)',
       'بركة السبع (طريق الدبايبة)', 'المظلات', 'القناطر', 'دروة',
       'النعناعية', 'أبو رقبة', 'كفر قورص', 'مجريا', 'شنشور', 'سمادون',
       'شعشاع', 'كفر الغريب', 'طهواى', 'دلهمو', 'أبو عوالى', 'جريس',
       'طليا', 'محلة سبك', 'البرانية', 'الكوادى', 'كفر السيد', 'الخور',
       'الحلواصى', 'مؤنسة', 'شوشاى', 'بوهة شطانوف', 'ساقية أبو شعرة',
       'كفر الحما', 'عزبة الفرعونية', 'محلة الدمنة', 'بدواى', 'البارمون',
       'كفر البرامون', 'البدالة', 'الدنابيق', 'شبرا وبدين', 'الخيارية',
       'كفر الأعجر', 'ديمشلت', 'نقيطة', 'منية سندوب', 'برج النور',
       'بلجاى', 'البقلية', 'ميت الأكراد', 'دماص', 'شاوه', 'كود الدربى',
       'تلبانة', 'تمى الأمديد', 'بنى عبيد', 'ميت على', 'برق العز', 'طناح',
       'أويش الحجر', 'كفر الشنهاب', 'منية سمنود', 'نوسا البحر', 'نبروه',
       'بسنديلة', 'ديمره', 'أورمان', 'المنيل', 'كفور العرب',
       'كفر الأصالى', 'كفر ديمره', 'ميت زنقر', 'بطره', 'شرنقاش',
       'ميت عنتر', 'ميت الكرما', 'المنشية', 'سندوب', 'نوسا الغيط',
       'فيشابنا', 'ميت دمسيس', 'شبراويش', 'سماحة', 'الديرس',
       'ميت أبو الحارث', 'جراح', 'شنيسة', 'بقطارس', 'الدير', 'سنجيد',
       'ميت العامل', 'أخطاب', 'الغراقة', 'ميت فضالة', 'ميت القرشى',
       'اتميدة', 'ميت محسن', 'سنتماى', 'أوليلة', 'إبيس البحيرة',
       'ميت العز', 'كفر النعيم', 'ميت ناجى', 'سرنجا', 'ميت أبو خالد',
       'ميت يعيش', 'هلا', 'بشلا', 'صهرجت', 'الدبونية', 'كفور البهايتة',
       'ميت الفرماوى', 'دنديط', 'كفر بهيدة', 'سنفا', 'كفر النعمان',
       'كفر سرنجا', 'التحرير', 'نجير', 'محلة دمنة', 'ميت طريف', 'الشركة',
       'منشأة عبد الرحمن', 'الصلاحات', 'أشمون الرمان', 'حادوس',
       'اليوسيفية', 'ظفر', 'ميت عدلان', 'الكردى', 'ديرب الخضر',
       'ميت تمامة', 'البجلات', 'الجنينة', 'الإتحاد', 'صان', 'مصر الجديدة',
       'الإسكندرية الجديدة', 'ميت مرجا سلسيل', 'البصراط', 'كفور الجمالية',
       'كفر علام', 'النسايمة', 'الأحمدية', 'الفروسات', 'العزيزة',
       'العامرة', 'المواجد', 'المنزلة الجديدة', 'الحوتة', 'ميت عاصم',
       'العصافرة', 'بهوت', 'الطيبة', 'تيرة', 'درين', 'كفر الأبحر',
       'ميت عباد', 'بانوب', 'نشا', 'طنيخ', 'الجزاير', 'الملعب',
       'الدمايرة', 'جميانة', 'وزير', 'زقلمة', 'القطنة', 'دملاش', 'قراش',
       'أبو دشيشة', 'الكردود', 'أبو طه', 'الهلالى', 'قلابشو', 'جالية',
       'الجرايدة', 'شرقية المعصرة', 'الستامونى', 'الخلالة', 'البنزينة',
       'حفير 57', 'الشوامى', 'بطرة', 'تفتيش كفر سعد', 'أم الرزق',
       'الصبرية', 'رأس الخليج', 'الأطرش', 'الوكالة', 'ترعة غنيم',
       'العيادية', 'أبو جلال', 'بنيامين', 'الدبوسى', 'الشناوى', 'الضهرية',
       'دنجواى', 'العوضية', 'بساط', 'البرامون', 'الحصص', 'منشأة النصر',
       'كفر شريف', 'أبو زاهر', 'كفر الترعة', 'كفر الحطبة', 'ديسط',
       'البشينى', 'البلامون', 'قرقيرة', 'غزالة', 'صدقا', 'أبو ياسين',
       'كفر عزام', 'الجلالية', 'كفر غنام', 'صافور', 'طوخ الأقلام', 'نوب',
       'الزهايرة', 'الحصاينة', 'ديو الوسطى', 'طنبول', 'ميت غراب',
       'شبراهور', 'الأورمان', 'شبرا سندى', 'برقين', 'برهمتوش',
       'أبو قراميط', 'بشمس', 'البكارية', 'منشأة أدهم', 'كفر قنصوة',
       'كفر الروك', 'المخزن', 'التمد', 'طنبارة', 'كفر الأمير', 'القاسمى',
       'أبو الصير', 'السمارة', 'أبو داوود', 'المقاطعة', 'الربع', 'البيضا',
       'تاج العز', 'المبهى', 'منشأة السلام', 'ميت صبرى أبو علم',
       'الحدادة', 'غازى مصبح', 'أبو المعاطى الباز', 'طلمبا بنى عبيد'],
      dtype=object)

In [23]:
data.to_excel('Sikka_data.xlsx',index=False)

In [3]:
lst=['الفيوم','الفيوم (مكيف)']
print([x.split()[0] for x in lst])

['الفيوم', 'الفيوم']